app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

app_logout:
    path: /logout
    methods: GET